# Generated by Django 5.1.5 on 2025-05-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freewebsitesubmission',
            name='project_description',
        ),
        migrations.RemoveField(
            model_name='freewebsitesubmission',
            name='project_name_or_idea',
        ),
        migrations.AddField(
            model_name='freewebsitesubmission',
            name='additional_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freewebsitesubmission',
            name='business_description',
            field=models.TextField(blank=True, help_text='Describe your business or organization.', null=True),
        ),
        migrations.AddField(
            model_name='freewebsitesubmission',
            name='business_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='freewebsitesubmission',
            name='has_brand_colors_fonts',
            field=models.BooleanField(default=False, verbose_name='Do you have brand colors and fonts?'),
        ),
        migrations.AddField(
            model_name='freewebsitesubmission',
            name='has_logo',
            field=models.BooleanField(default=False, verbose_name='Do you have a logo?'),
        ),
        migrations.AddField(
            model_name='freewebsitesubmission',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='freewebsitesubmission',
            name='key_competitors',
            field=models.TextField(blank=True, help_text='List 1-3 key competitors or websites you admire (and why, if possible).', null=True),
        ),
        migrations.AddField(
            model_name='freewebsitesubmission',
            name='main_goal_for_website',
            field=models.TextField(blank=True, help_text='What are your main goals for your website? Please list them, or describe your top priority.', null=True),
        ),
        migrations.AddField(
            model_name='freewebsitesubmission',
            name='reason_brand_awareness',
            field=models.BooleanField(default=False, verbose_name='Build brand awareness'),
        ),
        migrations.AddField(
            model_name='freewebsitesubmission',
            name='reason_leads_sales',
            field=models.BooleanField(default=False, verbose_name='Generate leads and sales'),
        ),
        migrations.AddField(
            model_name='freewebsitesubmission',
            name='reason_online_presence',
            field=models.BooleanField(default=False, verbose_name='Establish an online presence'),
        ),
        migrations.AddField(
            model_name='freewebsitesubmission',
            name='reason_other',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Other reason (Specify)'),
        ),
        migrations.AddField(
            model_name='freewebsitesubmission',
            name='reason_provide_info',
            field=models.BooleanField(default=False, verbose_name='Provide information to customers'),
        ),
        migrations.AddField(
            model_name='freewebsitesubmission',
            name='reason_showcase_products',
            field=models.BooleanField(default=False, verbose_name='Showcase products/services'),
        ),
        migrations.AddField(
            model_name='freewebsitesubmission',
            name='reason_wider_audience',
            field=models.BooleanField(default=False, verbose_name='Reach a wider audience'),
        ),
        migrations.AddField(
            model_name='freewebsitesubmission',
            name='services_offered',
            field=models.TextField(blank=True, help_text='What are your main services or products?', null=True),
        ),
        migrations.AddField(
            model_name='freewebsitesubmission',
            name='social_media_links',
            field=models.TextField(blank=True, help_text='Links to your social media profiles (e.g., Facebook, Instagram, LinkedIn), one per line.', null=True),
        ),
        migrations.AddField(
            model_name='freewebsitesubmission',
            name='target_audience_description',
            field=models.TextField(blank=True, help_text='Briefly describe your target audience or ideal customer.', null=True),
        ),
        migrations.AddField(
            model_name='freewebsitesubmission',
            name='will_provide_content',
            field=models.BooleanField(default=False, verbose_name='Are you willing to provide all the content (text and images) for your website?'),
        ),
        migrations.AddField(
            model_name='freewebsitesubmission',
            name='willing_to_provide_testimonial',
            field=models.BooleanField(default=False, verbose_name='Are you willing to provide a written or video testimonial if satisfied?'),
        ),
        migrations.AlterField(
            model_name='freewebsitesubmission',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='freewebsitesubmission',
            name='existing_website_url',
            field=models.URLField(blank=True, null=True, verbose_name='Existing Website (if any)'),
        ),
    ]
